backend:
  name: github
  repo: Machkeck/gatsby-starter-blog

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  - label: Gallery
    name: galleryImages
    identifier_field: name
    folder: content/gallery
    create: true
    widget: object
    fields:
      - { name: galleryName, label: Gallery Name }
      - label: Art Pieces
        name: pieces
        identifier_field: name
        widget: list
        fields: 
        - { name: title, label: Title }  
        - { label: Image, name: image, widget: image}
        - { name: size, label: Size }
  - label: Testimonials
    name: testimonials
    create: true
    folder: content/testimonials
    widget: list
    fields:
      - {label: Quote, name: quote, widget: string, default: Everything is awesome!}
      - label: Author
        name: author
        widget: object
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Avatar, name: avatar, widget: image}
  