backend:
  name: github
  repo: Machkeck/gatsby-starter-blog

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  - label: Gallery
    name: galleryImages
    folder: content/gallery
    create: true
    widget: list
    fields:
      - { name: galleryName, label: Gallery Name }
      - label: Art Pieces
        name: pieces
        widget: list
        fields: 
        - { label: Image, name: image, widget: image}
        - { name: title, label: Title }
        - { name: size, label: Size }
